version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: python:3.9-slim
    auth:
      username: santhosh270
      password: Catalyst@test123
  node:
    image: node:20
    auth:
      username: santhosh270
      password: Catalyst@test123
jobs:
  Deployment:
    runner: Machine
    image: image
    steps:
      - ls
      - pwd
      - cd mysite
      - python3.9 -m pip install django -t .
  CLIInstallation:
    runner: Machine
    image: node
    steps:
      - npm i -g zcatalyst-cli
      - catalyst -v
      - catalyst deploy --project 27833000000008058 --org 862569740 --token m_1004.af2a065472259ebceabb987ff97f77f7.5da80c8b3eecc12b25b41b95c3d9d5ef

stages:
  - name: Deployment
    jobs:
      - Deployment
      - CLIInstallation